src/storytime/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from storytime.stories import views
import settings

urlpatterns = [
	url(r'^accounts/login$',views.custom_login),
	url(r'^accounts/', include('registration.backends.default.urls')),
	url(r'^stories/create_stories/',views.create_stories),
	url(r'^stories/add_star',views.add_star),
	url(r'^comments/posted/$',views.custom_posted),
	url(r'^comments/', include('django_comments.urls')),
	url(r'^stories/read',views.read_stories),
	url(r'^media/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
	url(r'^profile/edit/image',views.image_edit),
	url(r'^profile/edit',views.user_edit),
	url(r'^profile/update_seen',views.update_seen),
	url(r'^profile',views.user_profile),
	url(r'^relationship/unfollow',views.unfollow),
	url(r'^relationship/follow',views.follow),
	url(r'^feed',views.feed),
	url(r'^bookmark',views.bookmark),
	url(r'^following',views.following),
	url(r'^load_notification',views.load_notification),
	url(r'^load_comment',views.load_comment),
	url(r'^notification',views.notification),
	url(r'^$',views.feed),
]

src/storytime/stories/models.py
from django.conf import settings
from django.db import models
from time import time
import datetime
import uuid
from sorl.thumbnail import ImageField

# Create your models here.
#Return the name to the Image file.
def get_upload_file_name(instance,filename):
	return "media/" + str(instance.user_id) + "/%s_%s" % (str(time()).replace('.','_'),filename)


# User can have multiple story
class Story(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	datetime = models.DateTimeField(auto_now_add=True, blank=False)
	starcount = models.IntegerField(default = 0)
	title = models.CharField(max_length = 200)
	storyid = models.UUIDField(unique=True, default=uuid.uuid4, editable=False)
	complete = models.BooleanField(default=False)
	commentcount = models.IntegerField(default = 0)
	
#Text will be inside story
class Text(models.Model):
	id = models.AutoField(primary_key=True)
	text = models.CharField(max_length = 200)
	position = models.IntegerField(default = 0)
	storyid = models.ForeignKey(Story)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,default = 1)
	
	
	
#Item will be inside story
class Image(models.Model):
	source = models.ImageField(upload_to = get_upload_file_name)
	position = models.IntegerField(default = 0)
	storyid = models.ForeignKey(Story)
	user = models.ForeignKey(settings.AUTH_USER_MODEL,default = 1)
	
class Profile_Image(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	image = models.ImageField(upload_to = get_upload_file_name,default='media/default/UserIconBlack.png')
	used = models.BooleanField(default=True)

class User_Info(models.Model):
	username = models.CharField(max_length = 200)
	user = models.OneToOneField(settings.AUTH_USER_MODEL,primary_key=True)
	desc = models.CharField(max_length = 200)
	profile_pic = models.ForeignKey(Profile_Image,null=True)
	
class Person(models.Model):
	name = models.ForeignKey(settings.AUTH_USER_MODEL)
	relationships = models.ManyToManyField('self', through='Relationship',
                                           symmetrical=False,
                                           related_name='related_to')
	def __unicode__(self):
		return '%s' %  (self.name)
	def add_relationship(self, person, status):
		relationship, created = Relationship.objects.get_or_create(
			from_person=self,
			to_person=person,
			status=status)
		return relationship

	def remove_relationship(self, person, status):
		Relationship.objects.filter(
			from_person=self,
			to_person=person,
			status=status).delete()
		return		
	def get_relationships(self, status):
		return self.relationships.filter(
			to_people__status=status,
			to_people__from_person=self)

	def get_related_to(self, status):
		return self.related_to.filter(
			from_people__status=status,
			from_people__to_person=self)

	def get_following(self):
		return self.get_relationships(RELATIONSHIP_FOLLOWING)

	def get_followers(self):
		return self.get_related_to(RELATIONSHIP_FOLLOWING)
#Relationship
RELATIONSHIP_FOLLOWING = 1
RELATIONSHIP_BLOCKED = 2
RELATIONSHIP_STATUSES = (
    (RELATIONSHIP_FOLLOWING, 'Following'),
    (RELATIONSHIP_BLOCKED, 'Blocked'),
)

class Relationship(models.Model):
    from_person = models.ForeignKey(Person, related_name='from_people')
    to_person = models.ForeignKey(Person, related_name='to_people')
    status = models.IntegerField(choices=RELATIONSHIP_STATUSES)
	
class Star(models.Model):
	storyid = models.ForeignKey(Story)
	user_id = models.ForeignKey(settings.AUTH_USER_MODEL)
	status = models.BooleanField(default=True)

src/storytime/stories/forms.py
from django import forms
from models import Text,Image,Story,User_Info,Profile_Image

class StoryForm(forms.ModelForm):
	class Meta:
		model = Story
		exclude =("user","id","datetime","like","storyid","starcount","complete")

class TextForm(forms.ModelForm):
	class Meta:
		model = Text
		exclude = ("storyid","user","textid")
		
class ImageForm(forms.ModelForm):
	class Meta:
		model = Image
		exclude = ("storyid","user","imageid")
		
class EditForm(forms.ModelForm):
	class Meta:
		model = User_Info
		exclude = ("profile_pic","user")
		
class EditFormImage(forms.ModelForm):
	class Meta:
		model = Profile_Image
		exclude = ("user","used")

src/storytime/stories/views.py
from django.shortcuts import render
from forms import TextForm,ImageForm,StoryForm,EditForm,EditFormImage
from django.template.context_processors import csrf
from django.forms.formsets import formset_factory
from models import Story,Text,Image,Person,RELATIONSHIP_FOLLOWING,User_Info,Profile_Image,Star
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.views import login
from django_comments.views.comments import post_comment
from django_comments.models import Comment
from django.utils.timesince import timesince
from sorl.thumbnail import get_thumbnail

def stream_readers(id,string):
	#Stream to all users who follows.
	user,created = Person.objects.get_or_create(name_id = id,id = id)
	followers = user.get_followers()
	import user_streams
	user_streams.add_stream_following(followers, string)
	return True
	

def stream_feed(id,string):
	#Stream to all users who follows.
	user,created = Person.objects.get_or_create(name_id = id,id = id)
	followers = user.get_followers()
	import user_streams
	user_streams.add_stream_feed(followers, string)
	
def stream_user(id,string):
	#Stream to all users who follows.
	user = User.objects.get(id = id)
	import user_streams
	user_streams.add_stream_item(user,string)
	return True

def add_star(request):
	if request.POST:
		#Get the story ID
		id = request.POST.get("storyid")
		#Fetch the story
		story = Story.objects.get(storyid = id)
		star = story.starcount
		#Get the star object. If it is not created, create 1 for user.
		starobject,created = Star.objects.get_or_create(storyid = story,user_id = request.user)
		if created:
			#Increment the story star by 1
			story.starcount = star + 1
			story.save()
			#Tell the author of story that the user has star the story
			stream_user(story.user_id,str(request.user.id)+":star your story:"+str(story.storyid))
			#Tell the user following that the user has star the story
			stream_readers(request.user.id,str(request.user.id)+":star a story:"+str(story.storyid))
			
		import json
		data = {}
		data['string'] = "<button type=\"button\" class=\"btn btn-success\" id = \"star\" value = \"" + str(story.storyid) + "\">Star <span>" + str(story.starcount) + "</span></button>"
		return HttpResponse(json.dumps(data), content_type = "application/json")
			
		

def custom_posted(request):
	if request.GET:
		commentid = request.GET.get('c')
		comment = Comment.objects.get(id = commentid)
		story = Story.objects.get(id = comment.object_pk)
		user = User.objects.get(id = story.user_id)
		profile = User_Info.objects.get(user_id = comment.user_id)
		#If another person that is not the author comment, notify the author.
		if not (user.id == comment.user_id):
			#Notify the story author that the user has commented.
			stream_user(user.id,str(comment.user_id) + ':has commented on your story:' + str(story.storyid))
			#Notify the follower of the user that the user has commented on this story
			stream_readers(request.user.id, str(comment.user_id) + ':has commented on a story:' + str(story.storyid))
		#Increase the comment count
		count = story.commentcount
		story.commentcount = count + 1
		story.save()
		#Get time
		time = timesince(comment.submit_date).split(', ')[0]
		import json
		data = {}
		div = "<div class = \"col-lg-10\"><div class = \"col-lg-1\" style = \"padding-left:0px; padding-right:0px; \">"
		try:
			image = profile.profile_pic.image
			im = get_thumbnail(image, '330x330', crop='center', quality=99)
			div = div + "<img class =\"img-circle img-responsive user-pic\" style=\"height:60px; width: 60px;\"  src = \"" + im.url + "\" /></div>"
		except:
			div = div + "<img class = \"img-circle img-responsive user-pic\" style=\"height:60px;  width: 60px; \"  src = \"/media/media/default/DefaultIconBlack_1.png\" /></div>"
		div = div + "<div class = \"col-lg-10\"><h4><a href = \"/profile?u=" + str(request.user.username) + "\">" + str(request.user.username) + "</a> " + " " + str(comment.comment) + "<h6>" + time + " ago</h6></h4></div></div><div class = \"col-lg-10\"><hr></div>"
		
		data['string'] = div
		return HttpResponse(json.dumps(data), content_type = "application/json")
			
	
def custom_login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect("/following/")
	else:
		return login(request)
		
# Create your views here.
def create_stories(request):
	if request.user.is_authenticated():
		if request.POST:
			current_user = request.user
			list_form = []
			#Get the story form
			storyform = StoryForm(request.POST,prefix = "Story")
			#Check if text and image exists
			if not (request.POST.getlist('text') and request.FILES.getlist('source')):
				from django.contrib import messages
				messages.add_message(request, messages.WARNING, 'Please insert at least 1 text and 1 image')
				return render_page(request,"create_stories.html","custom error")
				
			#Handle insertion for the title.
			if storyform.is_valid():
				story = storyform.save(commit = False)
				story.user_id = current_user.id
				story.save()
				#Handle insertion of the text
				for f,p in zip(request.POST.getlist('text'),request.POST.getlist('text_position')):
					text = TextForm(request.POST,{'position' : p,'text': f })
					if text.is_valid():
						addtext = text.save(commit = False)
						addtext.storyid_id = story.id
						addtext.user = current_user
						addtext.position = p
						addtext.text = f
						list_form.append(addtext);
					else:
						return render_page(request,"create_stories.html",{'form': text})


				#Handle insertion of the image
				for f,p in zip(request.FILES.getlist('source'),request.POST.getlist('position')):
					if f.size > 5000000:
						from django.contrib import messages
						messages.add_message(request, messages.WARNING, 'Image size should not be more than 5MB.')
						return render_page(request,"create_stories.html","custom error")
					form = ImageForm(request.POST, {'source': f })
					if form.is_valid():
						addimage = form.save(commit = False)
						addimage.storyid_id = story.id
						addimage.user = current_user
						addimage.position = p
						list_form.append(addimage);
					else:
						return render_page(request,"create_stories.html",{'form': form})
				#All form has been validated. Save it permanently
				for item_form in list_form:
					item_form.save()
				#Change the story complete to true so user can see it.
				story.complete = True;
				story.save();
				#Stream to all users who follows.				
				stream_feed(request.user.id,str(request.user.id) + ':' + str(story.storyid))
				
				return HttpRespondeRedirect('/complete')
			else:
				return render_page(request,"create_stories.html",{'form': storyform})
		else:
			return render_page(request,"create_stories.html","no error")
	else:
		return HttpRespondeRedirect("home.html")
		
#Render page. This is for create_stories
def render_page(request,html,form):
	#Create all the form required for the page
	imageform = ImageForm()
	textform = TextForm()
	storyform = StoryForm(prefix = "Story")
	profile = User_Info.objects.get(user_id = request.user.id)
	count = get_notification_count(request)
	notification = get_notification(request)
	args = {}
	#Add csrf security
	args.update(csrf(request))
	args['textform'] = textform
	args['imageform'] = imageform
	args['storyform'] = storyform
	args['profile'] = profile 
	args['notification'] = notification
	args['count'] = count
	
	#if there is an error add it inside the args
	if isinstance(form, dict):
		args['form'] = form['form']
	#Render the page with the args.
	return render(request,html,args)
	

#Read a specific story given the url.
def read_stories(request):
	#Import library needed
	from uuid import UUID
	from operator import attrgetter
	from itertools import chain
	
	if request.GET:
		#Get the story id from url.
		r_id = request.GET.get('s')
		try:
			val = UUID(r_id, version=4)
		except ValueError:
			# If it's a value error, then the string 
			# is not a valid hex code for a UUID.
			return HttpRespondeRedirect("/home")
			
		#Fetch the data necessary from database
		story = Story.objects.get(storyid = r_id)
		image = Image.objects.filter(storyid = story.id)
		text = Text.objects.filter(storyid = story.id)
		profile = User_Info.objects.get(user_id = request.user.id)
		author = User_Info.objects.get(user_id = story.user_id)
		
				
		comment = get_comment(story.id)

		#Combine result for text and image. Sort according to position
		combine = sorted(
						chain(text,image),
						key=attrgetter('position'))
		count = get_notification_count(request)
		notification = get_notification(request)
		args = {}
		args.update(csrf(request))
		args['story'] = story
		args['items'] = combine
		args['author'] = author
		args['profile'] = profile
		args['notification'] = notification
		args['count'] = count
		args['comments'] = comment
		return render (request,"read_stories.html",args)
	else:
		return HttpRespondeRedirect("/home")
	
#Show story from people who you followed	
def feed(request):
	if request.user.is_authenticated():
		#Create profile for user the first time.
		user,created = User_Info.objects.get_or_create(username = request.user.username,user_id = request.user.id)
		#Get the data streams for the user
		import user_streams
		items = user_streams.get_stream_feed(request.user)
		imagelist = []
		storylist = []
		for item in items:
			#Split the string into the user id and story id
			object = item.content.split(":")
			story = Story.objects.get(storyid = object[1])
			user_info = User_Info.objects.get(user_id = story.user_id)
			image = {}
			storyimage = Image.objects.filter(storyid = story.id).first()
			image['story'] = storyimage.source
			image['time'] = timesince(story.datetime).split(', ')[0]
			try:
				image['user'] = user_info.profile_pic.image
			except:
				image['user'] = None

			imagelist.append(image)
			storylist.append(story)
		profile = User_Info.objects.get(user_id = request.user.id)
		list = zip(storylist,imagelist)

src/storytime/templates/stories/bookmark.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/option.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/option_4.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/feed.css" %}">
	<script type="text/javascript" src="{% static "js/feed.js"%}"></script>
	
{% endblock %}
	
{% block content %}
	{% include "option.html" %}
	<div class = "row">
		{% for story,image in list %}
			<div class = "col-lg-4" style ="margin-top:20px;">

					<div class = "col-lg-12" >
						<a class = "story" href = "/stories/read/?s={{story.storyid}}" >
							{% thumbnail image.story "330x330" crop="center" as im %}
								<img class = "img-responsive img-rounded"  src="{{im.url}}" style = "text-align:center;">
							{% endthumbnail %}
						</a>
					</div>
					
					<div class = "col-lg-12">
						<h3 style = "text-align: center">{{story.title|truncatechars:30}}</h3>
					</div>
					<div class = "col-lg-12">
						<div class = "col-lg-2" style = "padding: 0;">
							{% if image.user %}
								{% thumbnail image.user "330x330" crop="center" as im %}
									<img class = "img-circle img-responsive user-pic" style="height: 50px; width: 50px;"  src = "{{im.url}}" data-toggle="dropdown" data-target="#"/> 
								{% endthumbnail %}
							{% else %}
								<img class = "img-circle img-responsive user-pic" style="height: 50px; width: 50px;"  src = "{{MEDIA_URL}}media/default/DefaultIconBlack_1.png" data-toggle="dropdown" /> 
							{% endif %}
						</div>
						<div class = "col-lg-10" style = "padding-left: 0;">
							<div  class = "col-lg-7">
								<h4>{{story.user.username}}</h4>
								<h5>{{image.time}} ago</h5>
							</div>
							<div class = "col-lg-2" style="display: table; height: 50px; width: 50px; background-image:url({% static "image\story\CommentIcon.png" %}); background-size: 50px 50px; "><h4 class = "text-white" style= "display: table-cell; vertical-align: middle; text-align: center;  padding-top: 5px;">{{story.commentcount}}</h4></div>
							<div class = "col-lg-2 col-lg-push-1" style=" display: table; height: 50px; width: 50px; background-image:url({% static "image\story\StarIcon.png" %}); background-size: 50px 50px;"><h4 class = "text-white" style= "display: table-cell; vertical-align: middle; text-align: center; padding-top: 5px;">{{story.starcount}}</h4></div>
							
						</div>
					</div>
			</div>

		{% endfor %}

	</div>
{% endblock %}
{% block footer %}
footer
{% endblock %}

src/storytime/templates/stories/create_stories.html
{% extends "base.html" %}
{% load staticfiles %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/create_story.css" %}">
	<script type="text/javascript" src="{% static "js/create_story.js"%}"></script>
{% endblock %}
{% block content %}
<br>
<div class = "row">
	<div class = "col-lg-10 col-lg-push-1">
		<div class = "col-lg-12">
			<h1 class = "text-green">Create new story</h1>
		</div>
		<div class = "col-lg-8">
			<h3>Create a new story. Make sure that the story contain at least an image and a text!</h3>
		</div>
		<div class = "col-lg-12">
			{% if messages %}
			<div class="messages">
				{% for message in messages %}
				<div{% if message.tags %} class="{{ message.tags }}"{% endif %}><h5 class = "error">{{ message }}</h5></div>
				{% endfor %}
			</div>
			{% endif %}
			
			{{ form.source.errors }}
			{% if form.title.errors %}
				<h5 class = "error">Please insert your title</h5>
			{% endif %}
		</div>
		<div class = "col-lg-12">
			<br>
		</div>
			<div class = "col-lg-12">
				<form action="/stories/create_stories/" method="post" enctype = "multipart/form-data">{% csrf_token %}
				<div class = "item">
					<div class = "row ">
						<div class = "col-lg-6">
							<label for="id_Story-title"><h4>Title:</h4></label>
						</div>
					</div>
					<div class = "row">
						<div class = "col-lg-8">
							<input class = "form-control" id="id_Story-title" maxlength="200" name="Story-title" type="text" placeholder="eg. Summer Vacation `15">
						</div>
					</div>
				</div>
					<br>
					<br>
			<div class = "row">
				<div class = "col-lg-12">
					<div id = "page" >
						<div id = "choice" class = "col-lg-3 ">
							<div id="addimage" class = "col-lg-12 btn btn-success" >
									<h4>Image</h4>
							</div>
							<div class = "col-lg-12">
								<hr>
							</div>
							<div id = "addtext" class = "col-lg-12 btn btn-success">
									<h4>Text</h4>
							</div>
						</div>
					</div>
				</div>
				<div class = "col-lg-12">
					<br>
					<br>
				</div>			
				<div class = "col-lg-12">
				<input type = "submit"  class = "btn btn-success" name = "submit" value = "Upload Story">
				</div>
				</form>
			</div>
		</div>
	</div>
</div>


{% endblock %}
{% block footer %}
footer
{% endblock %}

src/storytime/templates/stories/feed.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/option.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/option_1.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/feed.css" %}">
	<script type="text/javascript" src="{% static "js/feed.js"%}"></script>
	
{% endblock %}
	
{% block content %}
	{% include "option.html" %}
	<div class = "row">
		{% for story,image in list %}
			<div class = "col-lg-4" style ="margin-top:20px;">

					<div class = "col-lg-12" >
						<a class = "story" href = "/stories/read/?s={{story.storyid}}" >
							{% thumbnail image.story "330x330" crop="center" as im %}
								<img class = "img-responsive img-rounded"  src="{{im.url}}" style = "text-align:center;">
							{% endthumbnail %}
						</a>
					</div>
					
					<div class = "col-lg-12">
						<h3 style = "text-align: center">{{story.title|truncatechars:30}}</h3>
					</div>
					<div class = "col-lg-12">
						<div class = "col-lg-2" style = "padding: 0;">
							{% if image.user %}
								{% thumbnail image.user "330x330" crop="center" as im %}
									<img class = "img-circle img-responsive user-pic" style="height: 50px; width: 50px;"  src = "{{im.url}}" data-toggle="dropdown" data-target="#"/> 
								{% endthumbnail %}
							{% else %}
								<img class = "img-circle img-responsive user-pic" style="height: 50px; width: 50px;"  src = "{{MEDIA_URL}}media/default/DefaultIconBlack_1.png" data-toggle="dropdown" /> 
							{% endif %}
						</div>
						<div class = "col-lg-10" style = "padding-left: 0;">
							<div  class = "col-lg-7">
								<h4>{{story.user.username}}</h4>
								<h5>{{image.time}} ago</h5>
							</div>
							<div class = "col-lg-2" style="display: table; height: 50px; width: 50px; background-image:url({% static "image\story\CommentIcon.png" %}); background-size: 50px 50px; "><h4 class = "text-white" style= "display: table-cell; vertical-align: middle; text-align: center;  padding-top: 5px;">{{story.commentcount}}</h4></div>
							<div class = "col-lg-2 col-lg-push-1" style=" display: table; height: 50px; width: 50px; background-image:url({% static "image\story\StarIcon.png" %}); background-size: 50px 50px;"><h4 class = "text-white" style= "display: table-cell; vertical-align: middle; text-align: center; padding-top: 5px;">{{story.starcount}}</h4></div>
							
						</div>
					</div>
			</div>

		{% endfor %}

	</div>
{% endblock %}
{% block footer %}
footer
{% endblock %}

src/storytime/templates/stories/following.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/option.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/option_2.css" %}">
	<link rel="stylesheet" type="text/css" href="{% static "css/following.css" %}">
	<script type="text/javascript" src="{% static "js/following.js"%}"></script>
	
{% endblock %}
	
{% block content %}
	{% include "option.html" %}
	<div>
		{% for story,person in list %}
			<div class = "col-lg-12">
				<div class = "col-lg-1">
				{% if person.user_image %}
					{% thumbnail person.user_image "330x330" crop="center" as im %}
						<img class = "img-circle img-responsive user-pic" style="height: 60px; width: 60px;"  src = "{{im.url}}"/> 
					{% endthumbnail %}
				{% else %}
						<img class = "img-circle img-responsive user-pic" style="height: 60px; width: 60px;"  src = "{{MEDIA_URL}}media/default/DefaultIconBlack_1.png" data-toggle="dropdown" /> 
				{% endif %}
				</div>
				<div class = "col-lg-6" style = " display: table; ">
				<h3 style = "padding:0;">
					<a href = "/profile?u={{person.user1}}" >
						{{person.user1}} 
					</a>
					<span>{{person.content}}&nbsp;</span>  
					{% if person.user2 %}
						<a href = "/profile?u={{person.user2}}" >
							{{person.user2}} 
						</a>	
				</h3>
				<h6>{{person.time}} ago</h6>
				</div>
					{% else %}
				</h3>
				<h6>{{person.time}} ago</h6>
				</div>
				<div class = "col-lg-1">
						{% thumbnail person.story "330x330" crop="center" as im %}
							<a href = "/stories/read/?s={{story.storyid}}"><img class = "img-rounded img-responsive" style="height: 60px; width: 60px;"  src = "{{im.url}}" /></a>
						{% endthumbnail %}
					{% endif %}
				</div>
			
				<div class = "col-lg-12">
					<hr>
				</div>
			</div>

		{% endfor %}

	</div>
{% endblock %}
{% block footer %}
footer
{% endblock %}

src/storytime/templates/stories/image_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/user_edit.css" %}">
	<script type="text/javascript" src="{% static "js/user_edit.js"%}"></script>
{% endblock %}
{% block content %}
	<br>
	<div class = "row">
		<div class = "col-lg-6 col-lg-push-1">
			<h1 id = "editprofile">Change Profile Picture</h1>
		</div>
	</div>
	<div class = "row">
		<form  method="post" enctype="multipart/form-data">
			{% csrf_token %} 
			<div class = "col-lg-11 col-lg-push-1">
				<label for="id_image">Profile Picture:</label>
			</div>
			<div class = "col-lg-11 col-lg-push-1">
				<img id="preview" width="100" height="100">
			</div>
			<div class = "col-lg-11 col-lg-push-1">
				<input id="id_image" name="image" type="file" onchange="$('#preview')[0].src = window.URL.createObjectURL(this.files[0])">
			</div>
			<div class = "col-lg-11 col-lg-push-1">
				<input type="submit" value="Submit">
			</div>
		</form>
	</div>

{% endblock %}

src/storytime/templates/stories/user_edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load thumbnail %}
{% block predata %}
	<link rel="stylesheet" type="text/css" href="{% static "css/user_edit.css" %}">
	<script type="text/javascript" src="{% static "js/user_edit.js"%}"></script>
{% endblock %}
{% block content %}
	<br>
	<div class = "row">
		<div class = "col-lg-3 col-lg-push-1">
			<h1 id = "editprofile">Edit Profile</h1>
		</div>
		
	</div>
	<div class = "row">
		<form  method="post">
			{% csrf_token %} 
			<div class = "col-lg-11 col-lg-push-1">
				<label for="id_username">Name:</label>
			</div>
			<div class = "col-lg-6 col-lg-push-1 form-group">
				<input id="id_username" maxlength="200" name="username" type="text" value = "{{profile.username}}" class="form-control">
			</div>
			<div class = "col-lg-11 col-lg-push-1">
				<label for="id_desc">Profile Description:</label>
			</div>
			<div class = "col-lg-6 col-lg-push-1 form-group">
				<textarea id="id_desc" maxlength="200" name="desc" type="text" class="form-control">{{profile.desc}}</textarea>
			</div>
			<div class = "col-lg-11 col-lg-push-1">
				<input type="submit" value="Submit">
			</div>
		</form>
		<a href = "/profile/edit/image" class ="col-lg-6"></a>
	</div>

{% endblock %}